### ISSUE TITLE
LND client guide  - update

### ISSUE THREAD

**Issue by singlebeam** [minibolt-guide/minibolt#100]
The expected output for LND listening ports should include 8080 as it is now enabled by default.

![image](https://github.com/minibolt-guide/minibolt/assets/2654822/60b91efc-abb6-4289-ba89-267d96110e3a)

**Comment by twofaktor** [comment]
Good catch! It will be fixed in the next commit/release

**Comment by twofaktor** [comment]
Good catch! It will be fixed in the next commit/release. Thanks for your contribution!

**Comment by singlebeam** [comment]
Should the LND mobile app guide be adjusted as well? I don't think we need to add 'restlisten=0.0.0.0:8080' to LND config.

**Comment by twofaktor** [comment]
> Should the LND mobile app guide be adjusted as well? I don't think we need to add 'restlisten=0.0.0.0:8080' to the LND config.

I think, you are wrong, LND REST port needs to be reachable from another device out of localhost, listening only on the localhost would avoid that Zeus installed in another device (mobile phone) would access to the LND REST on the node

**Comment by singlebeam** [comment]
Ah yes, of course!  My mistake.  Thank you.
