### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by ZioIdelmino** [minibolt-guide/minibolt#91]
good morning please help me resolve an error during full minibolt node installation guide

### Minibolt

https://v2.minibolt.info/bitcoin/bitcoin/bitcoin-client

 "$ journalctl -f -u bitcoind
Feb 07 08:33:23  systemd[1]: Started Bitcoin Core Daemon.
Feb 07 08:33:23  bitcoind[1165]: Error: Settings file could not be read:
Feb 07 08:33:23  bitcoind[1165]: - Unable to parse settings file /home/bitcoin/.bitcoin/settings.json
Feb 07 08:33:23  systemd[1]: bitcoind.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 08:33:23  systemd[1]: bitcoind.service: Failed with result 'exit-code'.
Feb 07 08:33:23  systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 5.
Feb 07 08:33:23  systemd[1]: Stopped Bitcoin Core Daemon.
Feb 07 08:33:23  systemd[1]: bitcoind.service: Start request repeated too quickly.
Feb 07 08:33:23  systemd[1]: bitcoind.service: Failed with result 'exit-code'.
Feb 07 08:33:23  systemd[1]: Failed to start Bitcoin Core Daemon."

### Linux

- Hardware platform: intel amd64
- Operating system: [e.g, Ubuntu 
- Version: [ output of `lsb_jammy-d` ]

### tried to do backup file settings.json and edit with command :
#echo "{}" > settings.json

**Comment by twofaktor** [comment]
Probably you skipped an important step related with permissions. Review all the steps and if you don't get to solve it, try following the guide from the beginning again
