### ISSUE TITLE
Add a command line on Nginx installation procedure??

### ISSUE THREAD

**Issue by kami104** [minibolt-guide/minibolt#99]
*first of all, I am not a programmer or someone with high tech knowledge and maybe I found this problem for any failed previous procedure. Maybe what I did, generates a problem in next installation steps.*

I'm using Ubuntu server 24.04 LTS on a Lenovo ideapad Y700.

I was following [the guide](https://v2.minibolt.info/system/system/security) to install the Nginx server:

I got a failed test after create /etc/nginx/nginx.conf as indicated in the guide, deleting the available sites and creating the available streams directory:
`[emerg] 9992#9992: unknown directive "stream" in /etc/nginx/nginx.conf:20`
`nginx: configuration file /etc/nginx/nginx.conf test failed`

I searched on the web for this error and I found some people suggesting to install this package:
`apt install -y libnginx-mod-stream`
see [this site](https://stackoverflow.com/questions/50850900/nginx-unknown-directive-stream) and [other site](https://serverfault.com/questions/858067/unknown-directive-stream-in-etc-nginx-nginx-conf86).

The new installed package solved all issues. I attach a screenshot with comments on what I did.

![image](https://github.com/minibolt-guide/minibolt/assets/116915689/99660656-5a0b-4656-afc0-84b657a943ef)

I don't know if this "libnginx-mod-stream" package will make any problem in the future when I install bitcoin core or anything else. However at this moment, it solved my problem.

**Comment by twofaktor** [comment]
Hello, what OS did you installed?

Could you give me your output of this command?

`lsb_release -a`

**Comment by twofaktor** [comment]
Another different version of the Ubuntu operating system is not supported on MiniBolt. Closing this issue

![Screenshot_20240609_162509_org.mozilla.firefox_edit_15615754938241.jpg](https://github.com/minibolt-guide/minibolt/assets/89636253/53b0ed19-6ed0-4266-a533-ca20451b2cec)
